### PR TITLE
Branch fixes delete training 2

### LINKED ISSUE #87: Bug in the Deletion of Entire Trainings
-Trainings without students can be removed without issue
-Trainings with students cannot be removed without errors
- To update delete-training command to be handed using indexes instead of date-Time

### PR DESCRIPTION
**Pull request by sudogene**
**IMPORTANT: Search student by Id**
Given how tricky it is to maintain immutable student objects in an implicitly mutable manner (we modify a lot of stuff) and especially how the "same" student is being contained in both student list and INDIVIDUAL training, going forward, **we should point to students using Id values instead of equality checks.**
<br>

**A True Story Example  - Major bug**
1.  Create two trainings, T1 and T2
2. Add student Alex to T1 - `ts-add 1 1`
3. Add student Alex to T2 - `ts-add 2 1`
4. Delete training T1 - `delete-training 1`
   a. Loop through all students within T1 training list of students
   b. Remove T1's date time from that student's training schedule
   c. Update the `Model` using `model.setStudent(oldStudent, newStudent)`
<br>

There will be a `StudentNotFoundException` for 4c because:
* Alex object in T1 has one training session: T1
* Alex object in Model has two training sessions: T1 and T2
* `.equals()` will be false ==> Student not found

T1 stores the older Alex object and will not match any other newer Alex object IF we use `.equals()`. 
Hence, the next best thing we can use is `Id` which was created to be **unique and immutable**.
<br><br>

The bug above has been fixed.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteTrainingCommand.java [hunk 1]
```diff
@@ -66,6 +73,13 @@ private Student createEditedStudent(Student studentToEdit, Training trainingToDe
         return newStudent;
     }
 
+    private Student getStudentById(List<Student> studentsList, Id id) {
+        return studentsList.stream()
+                .filter(student -> student.getId().equals(id))
+                .findFirst()
+                .get();
```
Comment (yejiadong) [inline src/main/java/seedu/address/logic/commands/DeleteTrainingCommand.java]: if studentsList empty, is it safe that .get() will not throw a null pointer error?

**Review by yejiadong — APPROVED** [review]
LGTM.

File: src/main/java/seedu/address/logic/commands/DeleteTrainingCommand.java (hunk 1 above)
Comment (sudogene) [reply src/main/java/seedu/address/logic/commands/DeleteTrainingCommand.java]: It's assumed here that there will always be the Id existing in the list, is there a scenario that this wont happen?

Comment (yejiadong) [reply src/main/java/seedu/address/logic/commands/DeleteTrainingCommand.java]: makes sense, but might be good to include an assertion here in case of code changes in future

Comment (sudogene) [reply src/main/java/seedu/address/logic/commands/DeleteTrainingCommand.java]: yep thanks, shall do that. We see how this find by id goes, best is we abstract it to a util method

**Review by yejiadong — APPROVED** [review]
LGTM.
