### PR TITLE
Fix date bugs in datetime parsing, improved error messages

### LINKED ISSUE #184: [PE-D] Date time formatting for Trainings
I think one of the bugs is in handling of the date-time formats.

For the date 2021-02-32, it is an invalid format whilst adding 2021-02-31 gives us a rounding off to 2021-02-28, and when i try to add 2021-02-31 again it says the date is already added. By right it should not even be a valid date? I think its a corner case not covered yet.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Vielheim/ped#4

### LINKED ISSUE #198: [PE-D] Messages on the dashboard too long
Maybe can break up the error messages and add them in a newline so that user does nto have to scroll across to the right

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: munharsha/ped#8

### PR DESCRIPTION
**Pull request by yejiadong**
- Fix date bugs in datetime parsing
- Improved error messages for certain invalid inputs
- Set result window to wrap text automatically

### CODE REVIEW

File: src/main/java/seedu/canoe/logic/parser/TrainingCommandParser.java [hunk 1]
```diff
@@ -15,12 +13,11 @@
      * @throws ParseException if the user input does not conform the expected format
      */
     public TrainingCommand parse(String args) throws ParseException {
-        try {
-            LocalDateTime trainingTime = ParserUtil.parseTraining(args).getDateTime();
-            return new TrainingCommand(trainingTime);
-        } catch (ParseException pe) {
-            throw new ParseException(
-                    String.format(MESSAGE_INVALID_COMMAND_FORMAT, TrainingCommand.MESSAGE_USAGE), pe);
+        if (args.trim().equals("")) {
```
Comment (sudogene) [inline src/main/java/seedu/canoe/logic/parser/TrainingCommandParser.java]: minor suggestion: `args.trim().isEmpty()`

**Review by sudogene — APPROVED** [review]
LGTM

**Review by faqihisaninja — APPROVED** [review]
LGTM
